### ISSUE TITLE
'Run All SQL Statements' stop when setting delimiter to semi-colon

### ISSUE THREAD

**Issue by ztpHarley** [database-client/jdbc-adapter-server#6]

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version.
















At 2024-06-05 00:50:30, "Harley Frisby" ***@***.***> wrote:

Our release script include the line 'DELIMITER ;' at the start of certain procedures. When I attempt to run all statements, it stops once a line like this has been reached.

This is a new bug as it didn't happen previously
